### ISSUE TITLE
Problema no PM> Install-Package Danzor 

### ISSUE THREAD

**Issue by JeffersonGobi** [ycodeteam/danzor#7]
Olá, 

Estou utilizando o Visual Studio 2013, Framework 4.5 e quando tentei instalar o Package, o erro abaixo apareceu.

Install-Package : Could not install package 'Danzor 1.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4
.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact 
the package author.
At line:1 char:16
+ install-package <<<<  Danzor
    + CategoryInfo          : NotSpecified: (:) [Install-Package], InvalidOperationException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
 
Coloque nas especificações que necessita do .NET Framework 4.5.1

**Comment by yanjustino** [comment]
Obrigado @JeffersonGobi. Próxima semana vou publicar uma versão 4.0
